# Top 100 NumPy Questions for Interview

For this Notebook, we are here to try 100 NumPy questions

In [1]:
#1 Import NumPy as np
import numpy as np

In [5]:
#2 Print out the version of NumPy and show the config
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rogerli/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rogerli/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rogerli/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rogerli/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rogerli/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rogerli/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rogerli/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rogerli/opt/anaconda3/include']


In [6]:
#3 Setup an empty array, and length is 10
X = np.zeros(10)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
#4 Find the memory size of any array
X = np.array([1,2,3,4,5,6,7,8,9])
print(X)
print("%d bytes"%(X.size * X.itemsize))

[1 2 3 4 5 6 7 8 9]
72 bytes


In [12]:
#5 Get the info of add()
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [13]:
#6 Make an empty array length is 10, 5th value is 1.
X = np.zeros(10)
X[4] = 1
print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
#7 Make an array from 10 to 49
X = np.arange(10,50)
print(X)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
#8 Inverse an array
X = np.arange(10)
X = X[::-1]
print(X)

[9 8 7 6 5 4 3 2 1 0]


In [17]:
#9 Setup a 3 by 3 matrix, values from 0 to 8
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
#10 Located the Non-Zero values
X = np.array([1,2,0,0,4,0])
Y = np.nonzero(X)
print(Y)

(array([0, 1, 4]),)


In [27]:
#11 Make a 3 by 3 matrix
X = np.eye(3)
print(X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
#12 Make a random 3 by 3 by 3 array
X = np.random.random((3,3,3))
print(X)

[[[0.6556669  0.29526034 0.77251472]
  [0.1230537  0.96619917 0.9558856 ]
  [0.46248849 0.21296965 0.09395673]]

 [[0.92109392 0.87068119 0.07958919]
  [0.40688697 0.78798195 0.04745252]
  [0.72343362 0.23854727 0.70331933]]

 [[0.13720191 0.39784123 0.32217638]
  [0.77372954 0.92511799 0.20198996]
  [0.5013471  0.33100523 0.22213624]]]


In [31]:
#13 Make a 10 by 10 random array then find the maximum and minimum values
X = np.random.random((10,10))
print(X.min())
print(X.max())


0.006861908512894921
0.9841032499229628


In [38]:
#14 Create a random array with length 30, then find the mean
X = np.random.random((30))
Xmean = np.mean(X)
print(Xmean)

0.4710356476346941


In [42]:
#15 Create a 2D array, make the edge equals to 1, others are 0
X = np.zeros((10,10))
Y = np.ones((10,10))
X[1:-1,1:-1] = 1
Y[1:-1,1:-1] = 0
print(X)
print(Y)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [43]:
#16 Make the edges are 0
X = np.ones((5,5))
X = np.pad(X, pad_width=1, mode='constant', constant_values = 0)
print(X)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [51]:
#17 What are the results
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3 == 3*0.1)


nan
False
False
nan
False


In [53]:
#18 Create a 5 by 5 matrix, set value 1,2,3,4 under the diagonal
X = np.diag(1+np.arange(4), k=-1)
print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [57]:
#19 Create a 8 by 8 matrix, set it into chessboard
X = np.zeros((8,8), dtype = int)
X[1::2,::2] = 1
X[::2,1::2] = 1
X

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [70]:
#Special
# How does the : working in array
# 1st, create a array a = [1,2,3,4,5]
a = np.array([1,2,3,4,5])
print(a)
# If b=a[i:j], then copy a from i to j-1
b = a[1:3]
print(b)

# If i is empty, then i goes 0
print(a[:3])

# If j is empty, then j goes len(a)
print(a[2:])

# If i,j both empty, then copy a[]
print(a[:])

# If b = a[i:j:s], means copy a from i to j-1, step is s
print(a[0:5:2])

# If s is empty, then s=1
print(a[1:3:])

# If s<0, and i is empty then i goes -1
# and j is empty then j goes -len(a)-1
# So, if s is smaller than 1, then inverse the array a.
print(a[::-1])

[1 2 3 4 5]
[2 3]
[1 2 3]
[3 4 5]
[1 2 3 4 5]
[1 3 5]
[2 3]
[5 4 3 2 1]


In [75]:
#20 Think of a shape (6,7,8) array, show the index(x,y,z) at 100th element.
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [80]:
# Tips: 
# 1. For example: index is scalar, the matrix shape is 6*7*8
# then the position of the 100th index
# 100/(7*8)=1
# (100-1*7*8)/8 = 5
# (100-1*7*8-5*8)=4
# So the 100th index is array(1,5,4)