# Top 100 NumPy Questions for Interview

For this Notebook, we are here to try 100 NumPy questions

In [71]:
#1 Import NumPy as np
import numpy as np

In [5]:
#2 Print out the version of NumPy and show the config
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rogerli/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rogerli/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rogerli/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rogerli/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rogerli/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rogerli/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rogerli/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rogerli/opt/anaconda3/include']


In [6]:
#3 Setup an empty array, and length is 10
X = np.zeros(10)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
#4 Find the memory size of any array
X = np.array([1,2,3,4,5,6,7,8,9])
print(X)
print("%d bytes"%(X.size * X.itemsize))

[1 2 3 4 5 6 7 8 9]
72 bytes


In [12]:
#5 Get the info of add()
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [13]:
#6 Make an empty array length is 10, 5th value is 1.
X = np.zeros(10)
X[4] = 1
print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
#7 Make an array from 10 to 49
X = np.arange(10,50)
print(X)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
#8 Inverse an array
X = np.arange(10)
X = X[::-1]
print(X)

[9 8 7 6 5 4 3 2 1 0]


In [17]:
#9 Setup a 3 by 3 matrix, values from 0 to 8
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
#10 Located the Non-Zero values
X = np.array([1,2,0,0,4,0])
Y = np.nonzero(X)
print(Y)

(array([0, 1, 4]),)


In [27]:
#11 Make a 3 by 3 matrix
X = np.eye(3)
print(X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
#12 Make a random 3 by 3 by 3 array
X = np.random.random((3,3,3))
print(X)

[[[0.6556669  0.29526034 0.77251472]
  [0.1230537  0.96619917 0.9558856 ]
  [0.46248849 0.21296965 0.09395673]]

 [[0.92109392 0.87068119 0.07958919]
  [0.40688697 0.78798195 0.04745252]
  [0.72343362 0.23854727 0.70331933]]

 [[0.13720191 0.39784123 0.32217638]
  [0.77372954 0.92511799 0.20198996]
  [0.5013471  0.33100523 0.22213624]]]


In [31]:
#13 Make a 10 by 10 random array then find the maximum and minimum values
X = np.random.random((10,10))
print(X.min())
print(X.max())


0.006861908512894921
0.9841032499229628


In [38]:
#14 Create a random array with length 30, then find the mean
X = np.random.random((30))
Xmean = np.mean(X)
print(Xmean)

0.4710356476346941


In [42]:
#15 Create a 2D array, make the edge equals to 1, others are 0
X = np.zeros((10,10))
Y = np.ones((10,10))
X[1:-1,1:-1] = 1
Y[1:-1,1:-1] = 0
print(X)
print(Y)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [43]:
#16 Make the edges are 0
X = np.ones((5,5))
X = np.pad(X, pad_width=1, mode='constant', constant_values = 0)
print(X)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [51]:
#17 What are the results
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3 == 3*0.1)


nan
False
False
nan
False


In [53]:
#18 Create a 5 by 5 matrix, set value 1,2,3,4 under the diagonal
X = np.diag(1+np.arange(4), k=-1)
print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [57]:
#19 Create a 8 by 8 matrix, set it into chessboard
X = np.zeros((8,8), dtype = int)
X[1::2,::2] = 1
X[::2,1::2] = 1
X

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [70]:
#Special
# How does the : working in array
# 1st, create a array a = [1,2,3,4,5]
a = np.array([1,2,3,4,5])
print(a)
# If b=a[i:j], then copy a from i to j-1
b = a[1:3]
print(b)

# If i is empty, then i goes 0
print(a[:3])

# If j is empty, then j goes len(a)
print(a[2:])

# If i,j both empty, then copy a[]
print(a[:])

# If b = a[i:j:s], means copy a from i to j-1, step is s
print(a[0:5:2])

# If s is empty, then s=1
print(a[1:3:])

# If s<0, and i is empty then i goes -1
# and j is empty then j goes -len(a)-1
# So, if s is smaller than 1, then inverse the array a.
print(a[::-1])

[1 2 3 4 5]
[2 3]
[1 2 3]
[3 4 5]
[1 2 3 4 5]
[1 3 5]
[2 3]
[5 4 3 2 1]


In [75]:
#20 Think of a shape (6,7,8) array, show the index(x,y,z) at 100th element.
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [80]:
# Tips: 
# 1. For example: index is scalar, the matrix shape is 6*7*8
# then the position of the 100th index
# 100/(7*8)=1
# (100-1*7*8)/8 = 5
# (100-1*7*8-5*8)=4
# So the 100th index is array(1,5,4)

In [3]:
#21 Using commend tile to create a 8 by 8 chessboard matrix.
X = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(X)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
# Tips: First create an array as 0,1 1,0 then using tile()to copy and paste through X and Y
# For example, np.array(a,2) two times bigger of X direction
# np.array(a,(3,4)) three times and four times bigger of Y and X direction.(np.array(a,(Y,X)))
# np.array(a,(2,1)) two times bigger of Y and one time on X so X is constant only go for Y.

In [9]:
#22 5 by 5 matrix normalization.
X = np.random.random((5,5))
Xmax,Xmin = X.max(),X.min()
X = (X-Xmin)/(Xmax-Xmin)
print(X)

[[0.41701623 0.79378385 0.63112238 0.55775631 0.30859455]
 [0.18353783 0.77066539 0.75646891 0.83201569 0.62343622]
 [0.95096187 0.2241506  0.79454362 0.73701166 0.35524778]
 [0.52964466 0.52419236 0.41638379 0.55695933 1.        ]
 [0.44286487 0.28488848 0.16921225 0.         0.46292526]]


In [10]:
#Tips: For matrix normalization, the equation is 
# New_value = (value - value_min)/(value_max-value_min)

In [13]:
#23 Create four signed char which are for color(RGBA)
X = np.dtype([("r",np.ubyte,1),
            ("g",np.ubyte,1),
            ("b",np.ubyte,1),
            ("a",np.ubyte,1)])
X

/Users/rogerli/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [14]:
#Tips, For numpy ubyte as same as unsigned char in C.
# For Chinese Tutorial https://www.osgeo.cn/numpy/user/basics.types.html
# Shows the NumPy data type.

In [21]:
#24 Show the result of 5*3 times 3*2 matrix
X = np.dot(np.ones((5,3)), np.ones((3,2)))
X

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [26]:
#25 Inverse the values in an array which between 3 and 8
X = np.arange(11)
X[(3<X) & (X<8)]*=-1
print(X)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [27]:
#Tips: The difference between list, arange, range, and array
#1 list(), this is a inner Python function, the values in the list are not have to be the same type. All values
# skipped with ",".
#2 array(), same as the list(), but the dtype should be the same.
#3 range(), it's called range([start, stop, step]) it's doesn't contains the stop, and dtype is 'int'.
#4 arange(), it's called arange([start, stop, step)) it's doesn't contains the stop can use dtype 'float'.
# More details shows in tutorial: https://blog.csdn.net/bll1992/article/details/86437048

In [28]:
#26 Shows the results below:
print(sum(range(5),-1))


9


In [31]:
#Tips: For sum((iterable)[,start]), iterable means the target as array list or values, start means to add the 
# value after the sum operations. 
# Id start is empty, defualt value is 0.
#https://www.runoob.com/python/python-func-sum.html

In [42]:
#27, Think of a int array Z, which one is valid.
X = np.arange(5)
print(X**X)
print(2<<X>>2)
print(X<-X)
print(1j*X)
print(X/1/1)
print(X<X>X)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [44]:
#Tips, function << and >> means to shift the binary left and right,
# For example, 
# 1. 45<<1, means the binary of 45: 101101 shift left "1".
# then we get 1011010, convert it to decimal system. The result is 90.
# 2. 60>>2, means shift right two position.
# For binary 111100 >> 2, then we got 001111.
# So, the result is 15.
# More details: https://www.imooc.com/wenda/detail/572876

In [46]:
#28, Show the results:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/Users/rogerli/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/Users/rogerli/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [63]:
#Tips: 
# The usage of ndim, shape, dtype, astype
#1. ndim use for check the dimension of the array.
#2. shape use for check the shape for array or matrix, and dimensions
#3. dtype use for check the data type of array, like int32 and float64(special in NumPy)
# For example:
d1 = np.array([1,2,3,4,5,6])
d2 = np.array([[1,2,3],[4,5,6]])
d3 = np.array([[[1,2,3],[4,5,6]],[[6,5,4],[3,2,1]]])
print(d1.ndim, d2.ndim, d3.ndim)
print(d1.shape, d2.shape, d3.shape)
print(d1.dtype, d2.dtype, d3.dtype)
#
# For these results, 
# The shape of array d2 is one dimension, so it's only shows one value.
# For shape the result is (dim, counts)
# For three dimension matrix, the shape was checking for the entire matrix on the 
# direction Z, we can assum it like [A,B] and [C,D]
#4. astype is use for changing the data type. For example:
d1.astype('int32')

#int32 -->float64 is fine
#float64 --> int32 change to int
#string_ --> float64 if the string is all number should be fine.
str1 = np.array(['1.25','2.51','3.11'], dtype = np.string_)
str1.astype('float64')
#ref: https://blog.csdn.net/Da_wan/article/details/80518725

1 2 3
(6,) (2, 3) (2, 2, 3)
int64 int64 int64


array([1.25, 2.51, 3.11])

In [68]:
#29 How to make truncation from 0 point of float.
X = np.random.uniform(-10,+10,10)
print(X)
print(np.copysign(np.ceil(np.abs(X)),X))

[ 6.4566327  -0.74469667 -6.69536589 -5.18325235  4.83731731  4.74430513
  0.63969213 -1.47109274 -9.80034134 -2.03418578]
[  7.  -1.  -7.  -6.   5.   5.   1.  -2. -10.  -3.]


In [69]:
# Tips: random.uniform(a,b,c) means, array range is from a to b and has 
# counts as c.
# np.abs for absolut value
# np.ceil means return as int
# np.copysign(a,b) means copy the sign from b to a
# In this question, first find the absolute value, then make them int, and copy the sign from original X.

In [74]:
#30 Find the same element from any two arrays.
X1 = np.random.randint(0,10,10)
X2 = np.random.randint(0,10,10)
print(np.intersect1d(X1,X2))
print(X1,X2)
#Find the intersection.

[1 2 9]
[6 2 9 4 1 9 7 6 4 9] [2 2 3 9 2 9 2 8 1 1]
