# Top 100 NumPy Questions for Interview

For this Notebook, we are here to try 100 NumPy questions

## 1 Import NumPy as np

In [1]:
import numpy as np

## 2 Print out the version of NumPy and show the config

In [5]:
#
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rogerli/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rogerli/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rogerli/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rogerli/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rogerli/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rogerli/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rogerli/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rogerli/opt/anaconda3/include']


## 3 Setup an empty array, and length is 10

In [6]:
#
X = np.zeros(10)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4 Find the memory size of any array

In [11]:
#
X = np.array([1,2,3,4,5,6,7,8,9])
print(X)
print("%d bytes"%(X.size * X.itemsize))

[1 2 3 4 5 6 7 8 9]
72 bytes


## 5 Get the info of add()

In [12]:
#
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

## 6 Make an empty array length is 10, 5th value is 1.

In [13]:
#
X = np.zeros(10)
X[4] = 1
print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 7 Make an array from 10 to 49

In [14]:
#
X = np.arange(10,50)
print(X)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 8 Inverse an array

In [16]:
#
X = np.arange(10)
X = X[::-1]
print(X)

[9 8 7 6 5 4 3 2 1 0]


## 9 Setup a 3 by 3 matrix, values from 0 to 8

In [3]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 10 Located the Non-Zero values

In [26]:
#
X = np.array([1,2,0,0,4,0])
Y = np.nonzero(X)
print(Y)

(array([0, 1, 4]),)


## 11 Make a 3 by 3 matrix

In [27]:
#
X = np.eye(3)
print(X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 12 Make a random 3 by 3 by 3 array

In [28]:
#
X = np.random.random((3,3,3))
print(X)

[[[0.6556669  0.29526034 0.77251472]
  [0.1230537  0.96619917 0.9558856 ]
  [0.46248849 0.21296965 0.09395673]]

 [[0.92109392 0.87068119 0.07958919]
  [0.40688697 0.78798195 0.04745252]
  [0.72343362 0.23854727 0.70331933]]

 [[0.13720191 0.39784123 0.32217638]
  [0.77372954 0.92511799 0.20198996]
  [0.5013471  0.33100523 0.22213624]]]


## 13 Make a 10 by 10 random array then find the maximum and minimum values

In [31]:
#
X = np.random.random((10,10))
print(X.min())
print(X.max())


0.006861908512894921
0.9841032499229628


## 14 Create a random array with length 30, then find the mean

In [38]:
#
X = np.random.random((30))
Xmean = np.mean(X)
print(Xmean)

0.4710356476346941


## 15 Create a 2D array, make the edge equals to 1, others are 0

In [42]:
#
X = np.zeros((10,10))
Y = np.ones((10,10))
X[1:-1,1:-1] = 1
Y[1:-1,1:-1] = 0
print(X)
print(Y)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 16 Make the edges are 0

In [43]:
#
X = np.ones((5,5))
X = np.pad(X, pad_width=1, mode='constant', constant_values = 0)
print(X)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## 17 What are the results

In [51]:
#
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3 == 3*0.1)


nan
False
False
nan
False


## 18 Create a 5 by 5 matrix, set value 1,2,3,4 under the diagonal

In [53]:
#
X = np.diag(1+np.arange(4), k=-1)
print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 19 Create a 8 by 8 matrix, set it into chessboard

In [57]:
#
X = np.zeros((8,8), dtype = int)
X[1::2,::2] = 1
X[::2,1::2] = 1
X

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [70]:
#Special
# How does the : working in array
# 1st, create a array a = [1,2,3,4,5]
a = np.array([1,2,3,4,5])
print(a)
# If b=a[i:j], then copy a from i to j-1
b = a[1:3]
print(b)

# If i is empty, then i goes 0
print(a[:3])

# If j is empty, then j goes len(a)
print(a[2:])

# If i,j both empty, then copy a[]
print(a[:])

# If b = a[i:j:s], means copy a from i to j-1, step is s
print(a[0:5:2])

# If s is empty, then s=1
print(a[1:3:])

# If s<0, and i is empty then i goes -1
# and j is empty then j goes -len(a)-1
# So, if s is smaller than 1, then inverse the array a.
print(a[::-1])

[1 2 3 4 5]
[2 3]
[1 2 3]
[3 4 5]
[1 2 3 4 5]
[1 3 5]
[2 3]
[5 4 3 2 1]


## 20 Think of a shape (6,7,8) array, show the index(x,y,z) at 100th element.

In [75]:
#
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


###  Tips: 
### 1. For example: index is scalar, the matrix shape is 6*7*8
### then the position of the 100th index
### 100/(7*8)=1
### (100-1*7*8)/8 = 5
### (100-1*7*8-5*8)=4
### So the 100th index is array(1,5,4)

## 21 Using commend tile to create a 8 by 8 chessboard matrix.

In [3]:
#
X = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(X)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Tips: First create an array as 0,1 1,0 then using tile()to copy and paste through X and Y
### For example, np.array(a,2) two times bigger of X direction
### np.array(a,(3,4)) three times and four times bigger of Y and X direction.(np.array(a,(Y,X)))
### np.array(a,(2,1)) two times bigger of Y and one time on X so X is constant only go for Y.

## 22 5 by 5 matrix normalization.

In [9]:

X = np.random.random((5,5))
Xmax,Xmin = X.max(),X.min()
X = (X-Xmin)/(Xmax-Xmin)
print(X)

[[0.41701623 0.79378385 0.63112238 0.55775631 0.30859455]
 [0.18353783 0.77066539 0.75646891 0.83201569 0.62343622]
 [0.95096187 0.2241506  0.79454362 0.73701166 0.35524778]
 [0.52964466 0.52419236 0.41638379 0.55695933 1.        ]
 [0.44286487 0.28488848 0.16921225 0.         0.46292526]]


### Tips: For matrix normalization, the equation is 
### New_value = (value - value_min)/(value_max-value_min)

## 23 Create four signed char which are for color(RGBA)

In [13]:

X = np.dtype([("r",np.ubyte,1),
            ("g",np.ubyte,1),
            ("b",np.ubyte,1),
            ("a",np.ubyte,1)])
X

/Users/rogerli/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

### Tips, For numpy ubyte as same as unsigned char in C.
### For Chinese Tutorial https://www.osgeo.cn/numpy/user/basics.types.html
### Shows the NumPy data type.

## 24 Show the result of 5*3 times 3*2 matrix

In [21]:

X = np.dot(np.ones((5,3)), np.ones((3,2)))
X

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

## 25 Inverse the values in an array which between 3 and 8

In [26]:

X = np.arange(11)
X[(3<X) & (X<8)]*=-1
print(X)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


### Tips: The difference between list, arange, range, and array
### 1 list(), this is a inner Python function, the values in the list are not have to be the same type. All values
### skipped with ",".
### 2 array(), same as the list(), but the dtype should be the same.
### 3 range(), it's called range([start, stop, step]) it's doesn't contains the stop, and dtype is 'int'.
### 4 arange(), it's called arange([start, stop, step)) it's doesn't contains the stop can use dtype 'float'.
### More details shows in tutorial: https://blog.csdn.net/bll1992/article/details/86437048

## 26 Shows the results below:

In [28]:

print(sum(range(5),-1))


9


### Tips: For sum((iterable)[,start]), iterable means the target as array list or values, start means to add the 
### value after the sum operations. 
### Id start is empty, defualt value is 0.
### https://www.runoob.com/python/python-func-sum.html

## 27, Think of a int array Z, which one is valid.

In [42]:

X = np.arange(5)
print(X**X)
print(2<<X>>2)
print(X<-X)
print(1j*X)
print(X/1/1)
print(X<X>X)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Tips, function << and >> means to shift the binary left and right,
### For example, 
### 1. 45<<1, means the binary of 45: 101101 shift left "1".
### then we get 1011010, convert it to decimal system. The result is 90.
### 2. 60>>2, means shift right two position.
### For binary 111100 >> 2, then we got 001111.
### So, the result is 15.
### More details: https://www.imooc.com/wenda/detail/572876

## 28. Show the results:

In [46]:

print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/Users/rogerli/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/Users/rogerli/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [63]:
#Tips: 
# The usage of ndim, shape, dtype, astype
#1. ndim use for check the dimension of the array.
#2. shape use for check the shape for array or matrix, and dimensions
#3. dtype use for check the data type of array, like int32 and float64(special in NumPy)
# For example:
d1 = np.array([1,2,3,4,5,6])
d2 = np.array([[1,2,3],[4,5,6]])
d3 = np.array([[[1,2,3],[4,5,6]],[[6,5,4],[3,2,1]]])
print(d1.ndim, d2.ndim, d3.ndim)
print(d1.shape, d2.shape, d3.shape)
print(d1.dtype, d2.dtype, d3.dtype)
#
# For these results, 
# The shape of array d2 is one dimension, so it's only shows one value.
# For shape the result is (dim, counts)
# For three dimension matrix, the shape was checking for the entire matrix on the 
# direction Z, we can assum it like [A,B] and [C,D]
#4. astype is use for changing the data type. For example:
d1.astype('int32')

#int32 -->float64 is fine
#float64 --> int32 change to int
#string_ --> float64 if the string is all number should be fine.
str1 = np.array(['1.25','2.51','3.11'], dtype = np.string_)
str1.astype('float64')
#ref: https://blog.csdn.net/Da_wan/article/details/80518725

1 2 3
(6,) (2, 3) (2, 2, 3)
int64 int64 int64


array([1.25, 2.51, 3.11])

## 29 How to make truncation from 0 point of float.

In [68]:

X = np.random.uniform(-10,+10,10)
print(X)
print(np.copysign(np.ceil(np.abs(X)),X))

[ 6.4566327  -0.74469667 -6.69536589 -5.18325235  4.83731731  4.74430513
  0.63969213 -1.47109274 -9.80034134 -2.03418578]
[  7.  -1.  -7.  -6.   5.   5.   1.  -2. -10.  -3.]


### Tips: random.uniform(a,b,c) means, array range is from a to b and has 
### counts as c.
### np.abs for absolut value
### np.ceil means return as int
### np.copysign(a,b) means copy the sign from b to a
### In this question, first find the absolute value, then make them int, and copy the sign from original X.

## 30. How to cut position from 0 point for float

In [74]:

X1 = np.random.randint(0,10,10)
X2 = np.random.randint(0,10,10)
print(np.intersect1d(X1,X2))
print(X1,X2)
#Find the intersection.

[1 2 9]
[6 2 9 4 1 9 7 6 4 9] [2 2 3 9 2 9 2 8 1 1]


## 31 How to ignore all the warnings in NumPy ?????????

In [11]:

# Suicide mode on
defaults = np.seterr(all = "ignore")
X = np.ones(1)/0
X
# Back to sanity
_=np.seterr(**defaults)
Anequivalentway,withacontextmanager:
withnp.errstate(divide='ignore'):
X = np.ones(1)/0

SyntaxError: invalid syntax (<ipython-input-11-7021c574f3ac>, line 8)

## 32 True or False 

In [12]:

np.sqrt(-1) == np.emath.sqrt(-1)

False

### Tips: np.emath is alias for np.lib.scimath automatic domain

## 33 How to show the date for yesterday today and tomorrow

In [17]:

yesterday = np.datetime64('today','D')-np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print("yesterday is " + str(yesterday))
print("today is " + str(today))
print("tomorrow is " + str(tomorrow))


yesterday is 2020-07-26
today is 2020-07-27
tomorrow is 2020-07-28


'2020-07-27'

## 34 How to get all dates of July 2016

In [19]:

X = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(X)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 35 How to directely calculate (A+B)*(-A/2)(step by step)

In [22]:

A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B, out = B)

array([3., 3., 3.])

In [26]:
np.divide(A,2,out = A)

array([-0.25, -0.25, -0.25])

In [27]:
np.negative(A, out = A)

array([0.25, 0.25, 0.25])

In [29]:
np.multiply(A,B, out = A)

array([0.75, 0.75, 0.75])

## 36 Use 5 different ways to extract intern from random arrays
### 1

In [31]:

X = np.random.uniform(0,10,10)
print(X)
print(X-X%1)

[4.96418405 2.08723607 4.26077998 5.70393538 1.39451148 2.17674938
 4.30231799 4.10397283 1.41441616 0.52012431]
[4. 2. 4. 5. 1. 2. 4. 4. 1. 0.]


### 2

In [32]:

print(np.floor(X))

[4. 2. 4. 5. 1. 2. 4. 4. 1. 0.]


### 3

In [33]:

print(np.ceil(X)-1)


[4. 2. 4. 5. 1. 2. 4. 4. 1. 0.]


### Tips: Return positive int

### 4 

In [34]:

print(X.astype(int))


[4 2 4 5 1 2 4 4 1 0]


### Tip: Change datetype

### 5

In [35]:

print(np.trunc(X))


[4. 2. 4. 5. 1. 2. 4. 4. 1. 0.]


### Tip: Cut the in part

### 37 Create a 5 by 5 matrix, make each element from 0 to 4 

In [36]:

X = np.zeros((5,5))
X += np.arange(5)
print(X)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [40]:
#38 Create a function that can generate 10 int, and put them in an array
def generate():
    for x in range(10):
        yield x
X = np.fromiter(generate(),dtype=float,count=-1
            )
print(X)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39 Create a random array, length(10),range(0,1), beside(0,1)

In [41]:

X = np.linspace(0,1,11,endpoint=False)[1:]
print(X)



[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### Tips:
### Arithmetic progression
### np.linspace(start, stop, num=50(numbers of samples,default 50), endpoint=True/False(Include the ending point), 
### retstep = True/False skip space, dtype = datatype, axis = 0/1) 

In [42]:
#40 Sort a random array which lenth is 10
X = np.random.random(10)
X.sort()
print(X)

[0.01000764 0.04610798 0.08415229 0.1689019  0.37193323 0.4928562
 0.76409606 0.82943448 0.87232255 0.93832933]


In [3]:
#41 How to calculate the sum in an array faster than np.sum
X = np.arange(10)
np.add.reduce(X)

45

In [8]:
#42 For two random A and B how to check the equalty
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# 1,Compaire two values
equal = np.allclose(A,B)
print(A,B,equal)
# 2,Check both the shape and the element
equal = np.array_equal(A,B)
print(equal)

[1 0 1 1 1] [1 1 0 1 1] False
False


## 43 Create a read-only array 

In [4]:

X = np.zeros(10)
X.flags.writeable=False
X[0]=1

ValueError: assignment destination is read-only

## 44 Change a 10 by 2 matrix from Cartesian coordinates to polar coordinates 

In [12]:

Z= np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


[1.03306044 0.9042764  0.19432368 1.19564651 0.42152445 0.22284008
 0.88306987 0.54335884 1.15742941 1.18184491]
[1.21065776 0.87595587 1.49733858 0.78172239 0.66827045 1.5185447
 1.48881602 1.43047447 0.5641766  0.86590072]


### Tips:
### From cart(x,y) to polar(r,theata) coordinates
### Formula:
### r=sqrt(x^2 + y^2)
### theata = tan^-1(y/x)
### R=np.sqrt(X**2+Y**2)
### T=np.arctan2(Y,X)
### From polar to cart coordinates
### x = r*cos(theata)
### y = r*sin(theata) 

## 45 Create an array with length(10), then replace the maximum value to 1. 

In [15]:

X = np.random.random(10)
X[X.argmax()] = 1
print(X)

[0.90289773 0.18540761 0.78948761 0.84555054 0.299483   0.31364003
 0.79545419 1.         0.12158576 0.4077916 ]


## 46 Create a structured array, then make x and y covered [0,1]*[0,1] 

In [16]:

X = np.zeros((5,5),[('x',float),('y',float)])
X['x'],X['y']=np.meshgrid(np.linspace(0,1,5),
                         np.linspace(0,1,5))
print(X)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


## 47 Create two arrays, create Cauchy matrix C (Cij=1(xi-yj)) and determinant

In [25]:

X = np.arange(8)
Y = X + 0.5
C = 1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))
print(np.linalg.inv(C))
#Tips: Cauchy matrix Cij=1/Xi-Yj
# np.subtract means A - B 
# np.outer means A*B
# np.subtract.outer means Cauchy Matrix
# np.linalg.det means to calculate determinant
# np.linalg means linear algebra
# np.linalg.inv() means inverse the matrix
print(C)

3638.1636371179666
[[-0.32909095  0.15357578  0.03544056  0.01610935  0.00894964  0.00536978
   0.00322187  0.00168765]
 [-0.17720282 -0.24808395  0.17175043  0.04337132  0.02023995  0.01115263
   0.00636113  0.00322187]
 [-0.14498413 -0.11276543 -0.23420513  0.17742813  0.04599988  0.02129138
   0.01115263  0.00536978]
 [-0.13424456 -0.08770645 -0.10119975 -0.22999942  0.17888844  0.04599988
   0.02023995  0.00894964]
 [-0.13424456 -0.08054674 -0.07806838 -0.09857118 -0.22999942  0.17742813
   0.04337132  0.01610935]
 [-0.14498413 -0.08269465 -0.07360733 -0.07806838 -0.10119975 -0.23420513
   0.17175043  0.03544056]
 [-0.17720282 -0.09773004 -0.08269465 -0.08054674 -0.08770645 -0.11276543
  -0.24808395  0.15357578]
 [-0.32909095 -0.17720282 -0.14498413 -0.13424456 -0.13424456 -0.14498413
  -0.17720282 -0.32909095]]
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.222222

## 48 Print out Max and Min values of every numpy datatype 

In [26]:

for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### Tips:
### np.iinfo(dtype) means Machine limits for integer type
### np.finfo(dtype) means The equivalent for floating point data types.
### np.finfo(dtype).eps means The equivalent for floating point data types. 

## 49 How to print all values in an array

In [33]:



#np.set_printoptions(threshold=np.nan)
np.set_printoptions(threshold=100000000000)

Z = np.zeros((16,16))

print (Z)

# Tips: The threshold must be non-nan, then we just setup the threshold value very huge to replace
# np.nan

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 50 How to find the value which is the most close to the scalar value

In [36]:

X = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(X-v)).argmin()

print(X, v, X[index])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 76.38389674523162 76


### Tips:
### np.argmin() Means to find the minmum value in the array 

## 51. Create a structured array to represent point(x,y) and color (r,g,b)

In [6]:
X = np.zeros(10, [('position', [('X', float,1),
                               ('y',float, 1)]),
                 ('color', [('r',float, 1),
                           ('g', float, 1),
                           ('b', float,1)])])
print(X)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/Users/rogerli/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


## 52 For a coordinate shape random array(100,2) , find the
## distant between each points

### 1.

In [8]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.26704311 0.31969146 ... 0.38965829 0.35551387 0.2196879 ]
 [0.26704311 0.         0.17456208 ... 0.63603815 0.34579329 0.19715907]
 [0.31969146 0.17456208 0.         ... 0.70897461 0.19264288 0.11769372]
 ...
 [0.38965829 0.63603815 0.70897461 ... 0.         0.70806887 0.60303609]
 [0.35551387 0.34579329 0.19264288 ... 0.70806887 0.         0.1646251 ]
 [0.2196879  0.19715907 0.11769372 ... 0.60303609 0.1646251  0.        ]]


### 2
#### Tips: Much faster with scipy

In [10]:
import scipy
import scipy.spatial

In [11]:
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.26704311 0.31969146 ... 0.38965829 0.35551387 0.2196879 ]
 [0.26704311 0.         0.17456208 ... 0.63603815 0.34579329 0.19715907]
 [0.31969146 0.17456208 0.         ... 0.70897461 0.19264288 0.11769372]
 ...
 [0.38965829 0.63603815 0.70897461 ... 0.         0.70806887 0.60303609]
 [0.35551387 0.34579329 0.19264288 ... 0.70806887 0.         0.1646251 ]
 [0.2196879  0.19715907 0.11769372 ... 0.60303609 0.1646251  0.        ]]


## 53. How to convert 32bit float to integer

In [14]:
X = np.arange(10, dtype = np.float32)
X = X.astype(np.int32, copy = False)
print(X)

[0 1 2 3 4 5 6 7 8 9]


## 54. How to load these files

## 55. For NumPy array, what is the equavlent to enumerate

In [21]:
X = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(X):
    print(index, value)
for index, value in np.ndindex(X.shape):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


## 56. Create a Gaussian-like 2d array

In [23]:
X,Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D - mu)**2/(2.0*sigma**2)))
print(G)





[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

## 57. How to randomly put a value P into a 2D array

In [2]:
n=10
p=3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 58. Matrix elements minus mean values from each rows

In [6]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(X.mean(axis=1))
print(Y)

[0.37050306 0.47890796 0.50320327 0.40076162 0.4283857 ]
[[-0.35828975  0.25313646  0.49976484  0.08557548  0.08001486  0.05580463
  -0.36702606 -0.24179024 -0.25604418  0.24885396]
 [ 0.18832975  0.01959214  0.05210147 -0.46825608  0.28986931  0.09595185
   0.18601821 -0.33010897  0.08425186 -0.11774955]
 [ 0.32286055 -0.40352673 -0.05956481 -0.14125711  0.14141761  0.02429351
   0.18888022 -0.0788097  -0.38371662  0.38942309]
 [-0.30735936 -0.13597058 -0.32896748  0.34744031  0.39599276  0.20000484
  -0.14839973 -0.21871735 -0.35563629  0.55161288]
 [-0.41435844 -0.2467684   0.19534486  0.1068098  -0.08358893  0.27271503
  -0.08651499  0.25962352  0.25460969 -0.25787213]]


## 59. How to sort column n from an array

In [20]:
X = np.random.randint(0,10,(3,3))
print(X)
print(X[X[:,1].argsort()]) #Sort column 1


[[7 1 6]
 [7 0 7]
 [3 5 3]]
[[7 0 7]
 [7 1 6]
 [3 5 3]]


## 60. Find nan in a 2D array

In [23]:
X = np.random.randint(0,3,(3,10))
print(X)
print((~X.any(axis=0)).any())

[[2 1 2 2 2 1 2 1 1 1]
 [0 2 2 2 0 1 0 1 0 0]
 [0 1 0 1 0 0 0 1 2 2]]
False
